### ISSUE TITLE
Allow yielding across the C-call boundary

### ISSUE THREAD

**Issue by sci4me** [LuaJIT/LuaJIT#467] opened 2019-01-16 03:52 UTC
Believe it or not, I've hit a case where not being able to do this is a bit of a problem. I don't know what's involved in implementing this but, I really hope to see it happen.

**Comment by LaevusDexter** [comment] 2019-02-01 20:46
I think, u may use Tarantool's fibers.

**Comment by sci4me** [comment] 2019-02-01 21:13
> I think, u may use Tarantool's fibers, but it eats 60 kb for each.

As nice as that does look, it's really not a good option... I'd have to replace all code using coroutines to use that library. Plus I'd have to have an additional library.

What I have done is just ~~work~~ hack around the problem. It works... it's just not nice.

**Comment by daurnimator** [comment] 2019-02-01 22:54
Duplicate of #48

**Closed** 2019-12-08 21:31 UTC
Labels: duplicate
