### ISSUE TITLE
mcode_alloc failing on macOS arm64

### ISSUE THREAD

**Issue by bear24rw** [LuaJIT/LuaJIT#1030] opened 2023-07-07 22:37 UTC
I've started running into an issue where sometimes my application appears to hang due to what i believe is `mcode_alloc` failing to find an allocation. This seems potentially related to #285 and #283 but I've been unable to figure out a fix or workaround. I'm also not sure how to debug this issue further so let me know if you'd like me to collect any data.

The issue is also described by this reddit post: https://www.reddit.com/r/programming/comments/54e4xk/comment/d81ffwb/?utm_source=share&utm_medium=web2x&context=3

LuaJIT version ff6c496ba1b51ed360065cbc5259f62becd70daa

**Comment by bear24rw** [comment] 2023-07-07 22:40
In my application this problem only seems to occur if I also am mmaping things before calling into LuaJIT, if i switching my mmaps to regular mallocs the issue does not appear and mcode_alloc seems to find an allocation on the second probing iteration. Seems like I need to find a way to reserve some space for luajit to find but im unsure how to know where and how big that space needs to be.

**Comment by MikePall** [comment] 2023-07-08 17:49
Duplicate of #285.

**Closed by MikePall** 2023-07-08 17:49 UTC
Labels: duplicate
