### ISSUE TITLE
Will LUAI_MAXSHORTLEN in Lua-5.3 be supported in LuaJIT?

### ISSUE THREAD

**Issue by strrchr** [LuaJIT/LuaJIT#210] opened 2016-08-14 03:18 UTC
#define LUAI_MAXSHORTLEN	40
In Lua-5.3, long strings are not interned.
It seems that it solves many performance issues related to string interning.
In practice, long strings are read, processed, written, and never be keys in table.
I think the modification is related to string creation, comparison operators, table key hashing.

**Comment by MikePall** [comment] 2016-09-01 17:15
Duplicate of #168

**Closed by MikePall** 2016-09-01 17:15 UTC
Labels: duplicate
