### ISSUE TITLE
TDUP load forwarding after table rehashing

### ISSUE THREAD

**Issue by Buristan** [LuaJIT/LuaJIT#980] opened 2023-04-10 17:30 UTC
This issue is a follow-up for the commit d4c0c6e17ef7edf1f2893bc807746b80612e63e9 ("Fix TNEW load forwarding with instable types.").

<details>
  <summary> Reproducer for the TNEW (please, correct me if I'm wrong, and patch solves a different issue): </summary>

```sh
LUA_PATH="src/?.lua" src/luajit -Ohotloop=1 -jdump=i -e "
local r
for i = 6, 9 do
  local t = {i, i, i, i, i, i, i}
  -- Insert via ASTORE.
  t[i] = i
  t[1] = nil
  t[2] = nil
  t[3] = nil
  t[4] = nil
  t[5] = nil
  -- Rehash table. Array part is empty.
  t['1000'] = 1000
  -- Load via HLOAD.
  r = t[i]
end
"
```

Since the aforementioned patch assertion [replaced with `return 0`](https://github.com/LuaJIT/LuaJIT/blob/505e2c03de35e2718eef0d2d3660712e06dadf1f/src/lj_opt_mem.c#L215), which forbids forwarding, so issue is partially solved.

</details>

The similar case for TDUP is still possible. As for the different type of values to store:
```sh
LUA_PATH="src/?.lua;;" src/luajit -jdump=i -Ohotloop=1 -e "
local result
local expected = 'result'

-- TDUP different types.
for i = 6, 9 do
  local t = {1, 2, 3, 4, 5, 6, 7, 8}
  -- Insert via ASTORE.
  t[i] = expected
  -- Recorded on 7th iteration, change 8th value too.
  t[i + 1] = expected
  t[1] = nil
  t[2] = nil
  t[3] = nil
  t[4] = nil
  t[5] = nil
  t[6] = nil
  -- Rehash table. Array part is empty.
  t['1000'] = 1000
  result = t[8]
end
"
---- TRACE 1 start (command line):6
LuaJIT ASSERT lj_opt_mem.c:226: fwd_ahload: mismatched type in constant table
Aborted
```

So, for the same type of different values:
```sh
LUA_PATH="src/?.lua;;" src/luajit -jdump=i -Ohotloop=1 -e "
local result
local expected = 'result'

-- TDUP same type, different values.
for i = 6, 9 do
  local t = {1, 2, 3, 4, 5, 6, '7', '8'}
  t[i] = expected
  t[i + 1] = expected
  t[1] = nil
  t[2] = nil
  t[3] = nil
  t[4] = nil
  t[5] = nil
  t[6] = nil
  t['1000'] = 1000
  result = t[8]
end
"
---- TRACE 1 start (command line):6
LuaJIT ASSERT lj_record.c:171: rec_check_slots: slot 2 const mismatch: stack fffdff11730c3520 vs IR fffdff11730c3960
Aborted
```

To resolve the issue I search for any ASTORE in possibly the same table and, if find any, consider them as a conflict without forwarding anything.

<details>
  <summary> Suggested patch: </summary>

```diff
diff --git a/src/lj_opt_mem.c b/src/lj_opt_mem.c
index 09de2f05..15a03a37 100644
--- a/src/lj_opt_mem.c
+++ b/src/lj_opt_mem.c
@@ -196,6 +196,27 @@ static TRef fwd_ahload(jit_State *J, IRRef xref)
             goto cselim;
           ref2 = newref->prev;
         }
+      } else if (ir->o == IR_TDUP) {
+	IRIns *key = IR(xr->op2);
+	if (key->o == IR_KSLOT) key = IR(key->op1);
+	/* After rehashing of a table, HLOAD may point to the value inserted by
+	** ASTORE. For now, simply consider any ASTORE to the same table as a
+	** conflict without forwarding anything.
+	*/
+	if (irt_isnum(key->t)) {
+	  IRRef ref2 = J->chain[IR_ASTORE];
+	  while (ref2 > tab) {
+	    IRIns *astore = IR(ref2);
+	    IRIns *aref = IR(astore->op1);
+	    IRRef store_tab = IR(aref->op1)->op1;
+	    /* Same table to store means potential conflict. */
+	    if (store_tab == tab || aa_table(J, tab, store_tab) != ALIAS_NO) {
+	      lim = ref2;
+	      goto cselim;
+	    }
+	    ref2 = astore->prev;
+	  }
+	}
       }
       /* NEWREF inhibits CSE for HREF, and dependent FLOADs from HREFK/AREF.
       ** But the above search for conflicting stores was limited by xref.
```

Also, without condition `ir->o == IR_TDUP` the commit d4c0c6e17ef7edf1f2893bc807746b80612e63e9 may be reverted back for the assertion check (if it solves the similar issue) to check stores escaping alias analysis.

</details>

I've checked the patch on the following test with table aliasing:

<details>
  <summary> Test with table aliasing: </summary>

```sh
LUA_PATH="src/?.lua;;" src/luajit -jdump=i -Ohotloop=1 -e "
local result
local expected = 'result'
local alias_store = {{}, {}, {}, {}, {}}
for i = 6, 9 do
  local t = {1, 2, 3, 4, 5, 6, 7, 8}
  -- Store table, to be aliased later.
  alias_store[#alias_store + 1] = t
  local alias = alias_store[i]
  alias[i] = expected
  alias[i + 1] = expected
  alias[1] = nil
  alias[2] = nil
  alias[3] = nil
  alias[4] = nil
  alias[5] = nil
  alias[6] = nil
  alias['1000'] = 1000
  result = t[8]
end
"
```

</details>

<details>
  <summary> Benchmarks from LuaJIT-test-cleanup doesn't show a significant difference, but I apply it just in case. </summary>

| benchmark name | before (s) | after (s) |
|----------------|------------|-----------|
| array3d        | 0.19       | 0.19      |
| binary-trees   | 3.34       | 3.28      |
| chameneos      | 3.83       | 3.80      |
| coroutine-ring | 1.33       | 1.32      |
| euler14-bit    | 1.04       | 1.06      |
| fannkuch       | 6.67       | 6.67      |
| fasta          | 8.19       | 8.20      |
| life           | 0.46       | 0.47      |
| mandelbrot     | 2.69       | 2.69      |
| mandelbrot-bit | 1.94       | 1.93      |
| md5            | 1.60       | 1.58      |
| nbody          | 1.41       | 1.43      |
| nsieve         | 2.04       | 2.03      |
| nsieve-bit     | 1.49       | 1.46      |
| nsieve-bit-fp  | 4.44       | 4.63      |
| partialsums    | 0.70       | 0.73      |
| pidigits-nogmp | 3.51       | 3.54      |
| ray            | 2.03       | 2.08      |
| recursive-fib  | 1.09       | 1.60      |
| scimark-fft    | 5.65       | 5.65      |
| scimark-lu     | 3.46       | 3.42      |
| scimark-sor    | 2.46       | 2.46      |
| scimark-sparse | 5.18       | 5.12      |
| series         | 0.97       | 0.96      |
| spectral-norm  | 0.95       | 0.95      |

on
```sh
$ cat /proc/cpuinfo | grep "model name" | head -n1
model name      : Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
```
</details>

Issue #981 demonstrates the same assertion, but for a different reason.

**Comment by MikePall** [comment] 2023-04-16 11:50
I've committed a coarser fix. Thanks!

**Closed by MikePall** 2023-04-16 11:50 UTC
Labels: bug, 2.1, 2.0

**Comment by Buristan** [comment] 2023-04-16 16:25
Hi, Mike! Thanks for the fix!

As I can see, you don’t return assertion back, removed in the https://github.com/LuaJIT/LuaJIT/commit/d4c0c6e17ef7edf1f2893bc807746b80612e63e9.

May you, please, give an example of Lua code with type instability in loop-carried dependency, that you have mentioned in this commit?

**Comment by MikePall** [comment] 2023-04-16 17:11
Well, sigh, 2019 was a bad year. Here's the test that crashes/asserts without the change. I wasn't able to shorten this further or analyze the root cause. Maybe you have more luck and find another lurking bug.

```Lua
local y
for i=1,30 do
  local a = {{1, false, 3}}
  local b = {1, 2, 3}
  for i=1,2 do
    local c = a[i] or {}
    for _,k in ipairs(b) do
      y = c[k]
    end
  end
end
assert(y == nil)
```

**Comment by Buristan** [comment] 2023-04-16 18:56
Thanks a lot!
I’ll return with some news (I hope) in 2-3 weeks:).
