### ISSUE TITLE
Abusing __mode causes crash

### ISSUE THREAD

**Issue by Fraktality** [LuaJIT/LuaJIT#241] opened 2016-11-22 07:32 UTC
This code seems to crash the VM.

```lua
t = {
	[{''}] = ''
}
setmetatable(t, {__mode = 'aaaaaaaaaaaK'})
collectgarbage'collect'
tostring(next(t)) -- Crash
```
__mode must be at least 12 characters and contain an uppercase K to crash.

Tested with LuaJIT 2.0.4 and 2.1.0-beta2 (default flags) on Windows 10 x64.

**Comment by Fraktality** [comment] 2017-02-19 23:44
What's the purpose of K?  I don't see any mention of it in the Lua spec, and it isn't accounted for in the 5.1.1 source.

**Comment by daurnimator** [comment] 2017-02-20 00:27
> What's the purpose of K? I don't see any mention of it in the Lua spec, and it isn't accounted for in the 5.1.1 source.

Looks to be an undocumented luajit extension: https://github.com/LuaJIT/LuaJIT/blob/b93a1dd0c831cab22f98163d0dde792a493c0eef/src/lib_ffi.c#L813
https://github.com/LuaJIT/LuaJIT/blob/b93a1dd0c831cab22f98163d0dde792a493c0eef/src/lj_gc.c#L171
It seems to create a weakly keyed table... though reading through I can't exactly see how it's different (a K in the mode field does override an earlier "v", but that doesn't really seem relevant)

**Comment by Fraktality** [comment] 2017-02-20 21:28
> I think it ends up setting (most) bits to true in ->marked, which will probably be the source of the issues?

I don't think `marked` gets set when `K` is present.  `weak = (int)(~0u & ~LJ_GC_WEAKVAL)` sets the sign bit, so `weak > 0` can't be true.

The code a few lines down which [marks the hash part](https://github.com/LuaJIT/LuaJIT/blob/b93a1dd0c831cab22f98163d0dde792a493c0eef/src/lj_gc.c#L186) looks like the most likely culprit.

**Comment by javierguerragiraldez** [comment] 2017-03-03 11:26
Ok, as @Fraktality said, the fact that `weak` gets the sign bit set means that `t->marked` isn't affected, but the problem is that the table doesn't get into the `g->gc.weak` list, and on return from `gc_traverse_tab()`, it's not re-grayed either.

That means that when the weak key is collected, `gc_clearweak()` won't check this table to remove the pair, and we get a dangling pointer.

So, it seems that the 'K' flag is for internal use only.  I don't know why the FFI finalizer table needs it, but there should be some way to prevent other uses.  The simplest way seems to add a check on `setmetatable()`.

**Comment by MikePall** [comment] 2017-03-08 22:08
I've committed a proper fix.

**Closed by MikePall** 2017-03-08 22:08 UTC
Labels: 2.0, 2.1, BLOCKER 2.0, BLOCKER 2.1, bug
