### ISSUE TITLE
string.gmatch crashes (LUAJIT_ENABLE_GC64)

### ISSUE THREAD

**Issue by rbietin** [LuaJIT/LuaJIT#300] opened 2017-03-14 17:22 UTC
The following reproduces an issue with `string.gmatch` in LuaJIT 2.1 

```lua
-- simple function to split string by words using string.gmatch
local function split(str, delim)
	delim = delim or ","
	local result = {}
	local pat = "(.-)" .. delim .. "()"
	local lastPos = 1
	for part, pos in string.gmatch(str, pat) do
		table.insert(result, part)
		lastPos = pos
	end
	table.insert(result, string.sub(str, lastPos))
	return result
end

memoryFillMb = arg[1]

print("Filling memory with garbage.")

local setOfGarbage = {}
local oneMbString = "0"
for i = 1, 20 do
	oneMbString = oneMbString .. oneMbString
end
for i = 1, (memoryFillMb - math.floor(collectgarbage("count") / 1000)) do
	table.insert(setOfGarbage,  oneMbString .. i)
end

print("Used after filling memory: " .. math.floor(collectgarbage("count") / 1000) .. " Mb")

print("Generating some data.")
local lines = {}
for i = 1, 50000 do
	lines[i] = "This is a line of text #" .. i .. "."
end

print("Counting words in " .. #lines .. " lines.")
local sum = 0
for i = 1, #lines do
	sum = sum + #split(lines[i], " ")
end
print("Words count: " .. sum .. ".")

print("Running GC.")
collectgarbage()

print("Done.")
```

Running this code with `arg[1]` bigger then `3000` sometimes crashes.

works:
```
λ luajit.exe c:\temp\test.lua 2800
Filling memory with garbage.
Used after filling memory: 2867 Mb
Generating some data.
Counting words in 50000 lines.
Words count: 350000.
Running GC.
Done.
```

crashes:
```
λ luajit.exe c:\temp\test.lua 3800
Filling memory with garbage.
Used after filling memory: 3891 Mb
Generating some data.
Counting words in 50000 lines.
```

Test environment:

- Windows 10 (x64).
- 32 GB RAM (at least 20 is free).
- LuaJIT 2.1, build made with `gc64` flag.

**Comment by rweichler** [comment] 2017-03-17 00:58
It would help if you specified the commit, and maybe included a trace log

**Comment by MikePall** [comment] 2017-03-17 11:37
Confirmed bug.

It crashes in `lj_cont_dispatch` at `mov KBASE, LFUNC:KBASE->pc`. KBASE apparently doesn't point to a `GCFuncL`, which means the earlier `mov LFUNC:KBASE, [BASE-16]` loads something wrong from the stack. It looks like a 1-element GCstr instead.

Probably some issue with trace stitching and `LJ_FR2` frame layout. If somebody has the time to track this down, I'd be delighted.

**Comment by corsix** [comment] 2017-03-21 02:39
I think the fix is something similar in spirit to:
```diff
diff --git a/src/lj_emit_x86.h b/src/lj_emit_x86.h
index a6b8713..5207f9d 100644
--- a/src/lj_emit_x86.h
+++ b/src/lj_emit_x86.h
@@ -392,6 +392,7 @@ static void emit_loadk64(ASMState *as, Reg r, IRIns *ir)
       ir->i = (int32_t)(as->mctop - as->mcbot);
       as->mcbot += 8;
       as->mclim = as->mcbot + MCLIM_REDZONE;
+      lj_mcode_commitbot(as->J, as->mcbot);
     }
     emit_rmro(as, xo, r64, RID_RIP, (int32_t)mcpofs(as, as->mctop - ir->i));
 #else
```

Rationale: `recff_stitch` does `lj_ir_k64(J, IR_KNUM, u64ptr(pc))`, which can flow through to `emit_loadk64`, and in particular the "If all else fails, add the FP constant at the MCode area bottom" code path. If allocations at the bottom aren't committed at some point, then later traces can overwrite the constants of earlier traces, which can cause trace exits to restore the wrong PC to the Lua stack (i.e. an exit from the earlier trace can end up with the exit PC from the later trace), which can cause the next frame-return to improperly unwind the stack (as `PC_RA` affects unwinding), which can cause `mov LFUNC:KBASE, [BASE-16]` to load garbage. This chain of reasoning sounds rather tenuous and hypothetical, but I believe it is exactly what I'm observing in practice.

**Comment by MikePall** [comment] 2017-03-21 09:13
Great detective work! Fix applied.

**Closed by MikePall** 2017-03-21 09:13 UTC
Labels: 2.1, bug, GC64
