### ISSUE TITLE
Memory being allocated when it shouldn't

### ISSUE THREAD

**Issue by megagrump** [LuaJIT/LuaJIT#716] opened 2021-06-04 10:17 UTC
I apologize in advance for the weird test case. It is very fragile and I failed at making it any smaller but still reproduce the issue.
```lua
local ffi = require('ffi')

local state1 = ffi.new('struct { int64_t counter; }')
local state2 = ffi.new('struct { int fn; }')

local test1 = {
	step1 = function(self)
		state1.counter = state1.counter + 20
		self.step = self.step2
	end,

	step2 = function(self)
		if state1.counter > 0 then
			state1.counter = state1.counter - 1
		else
			self.step = self.step1
		end
	end
}

test1.step = test1.step2

local ops = {}
for i = 0, 340 do
	ops[i] = function() end
end

ops[0] = function() end
ops[1] = function() end
ops[2] = function() end
ops[3] = function() end
ops[4] = function() end
ops[5] = function() end
ops[6] = function() end
ops[7] = function() end
ops[8] = function() end
ops[10] = function() end
ops[65] = function() end
ops[66] = function() end
ops[67] = function() end
ops[68] = function() end
ops[69] = function() end
ops[70] = function() end
ops[71] = function() end
ops[72] = function() end
ops[249] = function() end
ops[250] = function() end
ops[251] = function() end
ops[252] = function() end
ops[253] = function() end
ops[254] = function() end
ops[256] = function() end
ops[257] = function() end
ops[259] = function() end
ops[260] = function() end

local function test2()
	for i = 1, 20 do
		ops[state2.fn]()
		state2.fn = state2.fn + 1
		if state2.fn == 341 then
			state2.fn = 0
		end
	end
end

collectgarbage('stop')

print("before A:", collectgarbage('count'))
for i = 1, 2e7 do
	test2()
	test1:step()
end
print("after A:", collectgarbage('count'))

collectgarbage()

print("before B:", collectgarbage('count'))
for i = 1, 2e7 do
	test1:step()
	test2()
end
print("after B:", collectgarbage('count'))
```
Example output:
```
before A:	56.6123046875
after A:	2875.6201171875
before B:	114.74609375
after B:	123.74609375
```
Loop A allocates a lot of memory for no discernible reason. Loop B, which does the same thing as A just in reverse, allocates almost no memory. 

Doing B before A solves the issue. Removing the additional assignments to `ops[x]`, or even just some of them, solves the issue as well. Using `int` instead of `int64_t` in `state1` solves it too.

What is causing the allocations, and how to avoid them?

**Comment by GitSparTV** [comment] 2021-06-04 10:20
Check if it's related to this issue: https://github.com/LuaJIT/LuaJIT/issues/675

**Comment by megagrump** [comment] 2021-06-04 10:23
The `collectgarbage('stop')` line is just there to illustrate the issue of memory being allocated. It has no relevance otherwise, and it is not there in the code where this behavior is an issue.

**Comment by GitSparTV** [comment] 2021-06-04 10:23
If not, probably these allocations are temporary boxed CData values.

**Comment by megagrump** [comment] 2021-06-04 10:43
Under the assumption that it's just the GC playing tricks on me and showing me misleading values: under what circumstances does an assignment to cdata create temporaries? Always? Should I refrain from using cdata like this in general if I want to avoid lots of temporary allocations? I'm talking many millions per second here.

**Comment by MikePall** [comment] 2021-06-04 12:10
The issue is not with the GC. There's an unpredictable megamorphic dispatch in a loop, so lots of traces are generated. You're seeing a side-effect of variables anchored to traces.

You can achieve much better performance with tailcall-based dispatch. This allows even traces across opcodes, which implicitly reconstructs the original control flow.

How to optimize an interpreter or a state machine is however out of scope for this issue tracker. Have a look at [https://blog.reverberate.org/2021/04/21/musttail-efficient-interpreters.html](this) for a recent take on it. Note that Lua has mandatory tailcalls (`return f()` idiom), which makes this easy.

**Closed by MikePall** 2021-06-04 12:10 UTC
Labels: question

**Comment by MikePall** [comment] 2025-08-12 09:09
LuaJIT handles recursion and tailcalls separately. Recursion is split into up- and down-recursion. A tailcall is just a goto to a function. If a series of tailcalls forms a loop, then LuaJIT compiles them like a loop. This is not a common pattern in Lua code, so there are strict limits for that (but they can be changed, even at runtime).

But there's a different issue with compiling an un-annotated interpreter with a trace compiler: region selection works at the control-flow level, but an interpreter is really data-driven (the program is data). Opcode implementations are formed into traces and loops, based on *aggregate* observed control-flow. This loses the precision needed to efficiently compile non-trivial interpreted programs.

Any solution would involve promoting the program counter of the interpreter to a first-level input for the region selection -- that's the 'meta' aspect about it. The implementation is left as an exercise for the reader.
