### ISSUE TITLE
0023 CRASH detected in gc_sweep due to a fault at or near 0x0000000000000000 leading to SIGSEGV

### ISSUE THREAD

**Issue by pwnhacker0x18** [LuaJIT/LuaJIT#1212] opened 2024-05-02 14:26 UTC
```
                     405: GCRef gc_sweep(g = (global_State *)0x7ffff7e533f0, p = (GCRef *)0x7ffff7e40ea0, lim = (uint32_t)<optimized out>) {
                       |||:
                       |||: /* Local reference: GCobj * o = 0x3ff0000000000000; */
                       |||: /* Local reference: GCRef * p = 0x7ffff7e40ea0; */
                       |||: /* Local reference: uint32_t lim = <optimized out>; */
                       409:   GCobj *o;
                       410:   while ((o = gcref(*p)) != NULL && lim-- > 0) {
                       411:     if (o->gch.gct == ~LJ_TTHREAD)  /* Need to sweep open upvalues, too. */
                       |||:
                       ---: }
                       at lj_gc.c:411

#1  0x000055555564afde in gc_onestep (/home/dolphinfuzz/fuzz_target_projects/lua-develop@f2cf17f5979/luajit2/src/luajit)
                       659: size_t gc_onestep(L = (lua_State *)0x7ffff7e53380) {
                       |||:
                       |||: /* Local reference: GCSize old = 224685; */
                       |||: /* Local reference: global_State * g = 0x7ffff7e533f0; */
                       687:   case GCSsweep: {
                       688:     GCSize old = g->gc.total;
                       689:     setmref(g->gc.sweep, gc_sweep(g, mref(g->gc.sweep, GCRef), GCSWEEPMAX));
                       |||:
                       ---: }
                       at lj_gc.c:689

#2  0x000055555564c9fa in lj_gc_step (/home/dolphinfuzz/fuzz_target_projects/lua-develop@f2cf17f5979/luajit2/src/luajit)
                       ???: int lj_gc_step(L = (lua_State *)0x7ffff7e53380) {
                       |||:
                       |||: /* Local reference: global_State * g = 0x7ffff7e533f0; */
                       |||: /* Local reference: GCSize lim = 480; */
                       |||: /* Local reference: lua_State * L = 0x7ffff7e53380; */
                       742:     g->gc.debt += g->gc.total - g->gc.threshold;
                       743:   do {
                       744:     lim -= (GCSize)gc_onestep(L);
                       |||:
                       ---: }
                       at lj_gc.c:744
```
[poc.txt](https://github.com/LuaJIT/LuaJIT/files/15189739/poc.txt)

**Comment by corsix** [comment] 2024-05-09 20:52
Using git head (5790d253972c9d78a), the poc.txt either seems to terminate cleanly, or print an infinite amount of spam. Neither scenario reproduces a segfault.

**Comment by Buristan** [comment] 2024-05-11 07:52
Looks like a duplicate of #1169. The issue is reproduced only with cae361187e7e1e3545353fb560c032cdace32d5f ("Prevent down-recursion for side traces.") reversed.

**Closed** 2024-05-12 18:27 UTC
Labels: duplicate
