### ISSUE TITLE
macOS M1 FFI calls with 9 or more uint8_t arguments unimplemented

### ISSUE THREAD

**Issue by elliottslaughter** [LuaJIT/LuaJIT#888] opened 2022-08-23 20:46 UTC
LuaJIT FFI on macOS M1 (ARM64) seems to not yet implement calls to C functions with 9 or more `uint8_t` arguments.

Reproducer:

`bug.c`:

```c
#include <stdint.h>

int8_t f(int8_t x0, int8_t x1, int8_t x2, int8_t x3, int8_t x4, int8_t x5, int8_t x6, int8_t x7, int8_t x8, int8_t x9) {
  return x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9;
}
```

`bug.lua`:

```lua
local ffi = require("ffi")

ffi.cdef [[
int8_t f(int8_t x0, int8_t x1, int8_t x2, int8_t x3, int8_t x4, int8_t x5, int8_t x6, int8_t x7, int8_t x8, int8_t x9);
]]

local c = ffi.load("libbug")

print(c.f(0, 1, 2, 3, 4, 5, 6, 7, 8, 9))
```

Then run:

```
clang bug.c -o libbug.dylib -shared -Wall
luajit bug.lua
```

It should print `45`, but on macOS M1 it produces:

```
bug.lua:9: NYI: cannot call this C function (yet)
stack traceback:
	[C]: in function 'f'
	bug.lua:9: in main chunk
```

The corresponding test passes on macOS x86_64, Linux (both x86_64 and ARM64), etc.

While we're here, it would be good to also check `uint16_t` etc. and numbers of arguments > 9. These are left as an exercise to the reader.

Versions:

  * LuaJIT 50936d784474747b4569d988767f1b5bab8bb6d0
  * macOS 12.5.1
  * `uname -a`: Darwin localhost 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64
  * Xcode 13.4.1
  * Apple clang version 13.1.6 (clang-1316.0.21.2.5), target arm64-apple-darwin21.6.0

**Comment by MikePall** [comment] 2022-08-24 08:45
Duplicate of #205

**Closed by MikePall** 2022-08-24 08:45 UTC
Labels: duplicate
