### ISSUE TITLE
a+1 = inf 

### ISSUE THREAD

**Issue by Pad0y** [LuaJIT/LuaJIT#747] opened 2021-09-28 02:32 UTC
under what circumstances will the variable plus 1 equal inf, I am sure it is not a bug of luajit

**Comment by MikePall** [comment] 2021-09-29 10:08
If you are sure it's not a bug, then why are you opening an issue here?

Questions and homework about floating point arithmetic are best resolved by searching for said keywords.

**Closed by MikePall** 2021-09-29 10:08 UTC
Labels: invalid
