### ISSUE TITLE
0004 CRASH detected in 0x0000555516f9d63c due to a fault at or near 0x0000000000000008 leading to SIGSEGV

### ISSUE THREAD

**Issue by pwnhacker0x18** [LuaJIT/LuaJIT#1213] opened 2024-05-02 14:29 UTC
```
-
```
[poc.txt](https://github.com/LuaJIT/LuaJIT/files/15189775/poc.txt)

**Comment by corsix** [comment] 2024-05-09 20:53
Using git head (5790d253972c9d78a), the poc.txt seems print an infinite amount of spam rather than reproducing a segfault.

**Comment by Buristan** [comment] 2024-05-11 07:52
Looks like a duplicate of #1169. The issue is reproduced only with cae361187e7e1e3545353fb560c032cdace32d5f ("Prevent down-recursion for side traces.") reversed.

**Closed** 2024-05-12 18:26 UTC
Labels: duplicate
