### ISSUE TITLE
Q: Best approach to build 32 bit luajit byte code on 64 bit macOS host

### ISSUE THREAD

**Issue by JCash** [LuaJIT/LuaJIT#883] opened 2022-08-11 09:31 UTC
([Related question](https://github.com/LuaJIT/LuaJIT/issues/725))

I'm in the process of updating our LuaJIT libraries + tools:
In our use case we need to be able to generate LuaJIT byte code for 32 bit targets, on our 64 bit hosts.
In particular, I'm on macOS which cannot (easily) build for 32 bit hosts (i.e. I cannot produce a luajit-32).

Previously, we used the prepackaged version in the "releases" section. But that section is now removed in the LuaJIT repo.
(Fortunately we still have a copy of that 32bit luajit exe)

Is there is a best practice for this?
Does anyone else have this use case?

If not, then perhaps we could outline what steps would need to be taken in order to be able to compile the luajit exe with 32 bit support. Then perhaps I can make a PR with this improvement.

**Comment by zhaozg** [comment] 2022-08-11 09:39
> In particular, I'm on macOS which cannot (easily) build for 32 bit hosts (i.e. I cannot produce a luajit-32).

I use docker to build luajit 32 on macos.

**Comment by MikePall** [comment] 2022-08-15 12:24
Duplicate of #664

**Closed by MikePall** 2022-08-15 12:24 UTC
Labels: duplicate
